language: cpp
sudo: false
dist: bionic

notifications:
  slack: c0demonk3ys:gnjXYwuoMOBnffg9h8YnlLyE

matrix:
  include:
    - name: "GCC Debug"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: [ 'g++-7', 'xorg-dev', 'libglu1-mesa-dev', 'libsfml-dev', 'libpython3.8-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "GCC Release"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: [ 'g++-7', 'xorg-dev', 'libglu1-mesa-dev', 'libsfml-dev', 'libpython3.8-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "Clang Debug"
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: [ 'clang-6.0', 'xorg-dev', 'libglu1-mesa-dev', 'libsfml-dev', 'libpython3.8-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "Clang Release"
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: [ 'clang-6.0', 'xorg-dev', 'libglu1-mesa-dev', 'libsfml-dev', 'libpython3.8-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

before_install:
  - mkdir $HOME/cmake
  - wget -O $HOME/cmake/install.sh https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.sh
  - bash $HOME/cmake/install.sh --prefix=$HOME/cmake --skip-license --exclude-subdir
  - export PATH="$HOME/cmake/bin:$PATH"
  - cmake --version
  - env

script:
  - cd "$TRAVIS_BUILD_DIR/build"
  - export CMAKE_MODULE_PATH=/usr/share/SFML/cmake/Modules/
  - cmake -DVERBOSE_LOGGING=ON -DBUILD_DEMOS=ON -DBUILD_TESTS=ON -G "Unix Makefiles" "$TRAVIS_BUILD_DIR"
  - make -l all test
