
IF(CMAKE_COMPILER_IS_GNUXX OR ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang")
    SET(CMAKE_CXX_FLAGS "-std=c++14")
    ADD_DEFINITIONS(-D_XOPEN_SOURCE=700)
    ADD_COMPILE_OPTIONS(-Wall -Wextra)
ELSEIF(MSVC)
    INCLUDE(ProcessorCount)
    ProcessorCount(PROC_COUNT)
    MESSAGE("Building with ${PROC_COUNT} cores")

    ADD_DEFINITIONS(/D_CRT_SECURE_NO_WARNINGS)
    SET(CMAKE_CXX_FLAGS 
        "${CMAKE_CXX_FLAGS} /EHsc /MP${PROC_COUNT}")
    SET(CMAKE_EXE_LINKER_FLAGS
        "${CMAKE_EXE_LINKER_FLAGS /NODEFAULTLIB:LIBCMT")
ENDIF()

